version: '3.8'

services:
  app:
    build: .
    ports:
      - "1050:1050"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Lucky_Social_Network
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=19111993
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=Lucky_Social_Network
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=19111993
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: