CREATE TABLE ad_schedule
(
    ad_id       BIGINT                 NOT NULL,
    day_of_week SMALLINT               NOT NULL,
    start_time  time WITHOUT TIME ZONE NOT NULL,
    end_time    time WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE ad_target_groups
(
    ad_id    BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT pk_ad_target_groups PRIMARY KEY (ad_id, group_id)
);

CREATE TABLE advertisements
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    content      VARCHAR(1000)                           NOT NULL,
    image_url    VARCHAR(255),
    external_url VARCHAR(255),
    user_id      BIGINT                                  NOT NULL,
    group_id     BIGINT,
    start_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    is_active    BOOLEAN                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_advertisements PRIMARY KEY (id)
);

CREATE TABLE group_memberships
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    group_id         BIGINT                                  NOT NULL,
    role             VARCHAR(255)                            NOT NULL,
    joined_at        TIMESTAMP WITHOUT TIME ZONE,
    role_assigned_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_group_memberships PRIMARY KEY (id)
);

ALTER TABLE advertisements
    ADD CONSTRAINT FK_ADVERTISEMENTS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE advertisements
    ADD CONSTRAINT FK_ADVERTISEMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE group_memberships
    ADD CONSTRAINT FK_GROUP_MEMBERSHIPS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_memberships
    ADD CONSTRAINT FK_GROUP_MEMBERSHIPS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE ad_schedule
    ADD CONSTRAINT fk_ad_schedule_on_ad FOREIGN KEY (ad_id) REFERENCES advertisements (id);

ALTER TABLE ad_target_groups
    ADD CONSTRAINT fk_adtargro_on_ad FOREIGN KEY (ad_id) REFERENCES advertisements (id);

ALTER TABLE ad_target_groups
    ADD CONSTRAINT fk_adtargro_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

DROP TABLE post_likes CASCADE;

ALTER TABLE user_daily_activity
    DROP COLUMN activity_date;

ALTER TABLE user_daily_activity
    DROP COLUMN session_count;

ALTER TABLE user_daily_activity
    DROP COLUMN total_minutes;

ALTER TABLE groups
    DROP COLUMN avatar_dropbox_path;

ALTER TABLE users
    DROP COLUMN last_activity;

ALTER TABLE users
    DROP COLUMN preferred_language;

ALTER TABLE users
    DROP COLUMN session_start;

ALTER TABLE users
    DROP COLUMN timezone;

ALTER TABLE users
    DROP COLUMN total_online_time_minutes;

ALTER TABLE user_daily_activity
    ALTER COLUMN user_id SET NOT NULL;